languageCode = "zh-cn"
title = "FiveM中文文档"
theme = "docsy"
contentDir = "content"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
baseURL = "/"
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

disablePathToLower = true
enableGitInfo = true

[outputs]
home = ["HTML", "RSS"]

[params]
disableHomeIcon = true
editURL = "https://github.com/malagebe/fivem-docs/edit/master/content/"
github_repo = "https://github.com/malagebe/fivem-docs"
#github_project_repo = "https://github.com/citizenfx/fivem"
offlineSearch = true

time_format_default = "2006-01-02"

[blackfriday]
hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "FiveM中文网"
url = "https://fivem.net.cn"
weight = 10

[[menu.main]]
name = "FiveM官网"
url = "https://fivem.net"
weight = 30

[[menu.main]]
name = "点击加入交流群"
url = "https://jq.qq.com/?_wv=1027&k=qACW1VY3"
weight = 40

[params.ui]
sidebar_menu_compact = true
